trigger:
- main  # or your desired branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Replace with the exact name of your service connection
  azureServiceConnection: 'my-azure-connection'
  terraformWorkingDirectory: './terraform'
  terraformVersion: '1.3.5'

stages:
- stage: DeployInfrastructure
  displayName: "Deploy Entire Infrastructure in Private Mode"
  jobs:
  - job: Terraform
    displayName: "Run Terraform to deploy Private AKS, ACR, and Endpoints"
    steps:
    - checkout: self

    - task: AzureCLI@2
      displayName: "Install Terraform, Initialize, Plan & Apply"
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          set -e
          echo "Installing Terraform version $(terraformVersion)..."
          wget https://releases.hashicorp.com/terraform/$(terraformVersion)/terraform_$(terraformVersion)_linux_amd64.zip
          unzip terraform_$(terraformVersion)_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform --version

          # Navigate to the Terraform working directory
          cd $(terraformWorkingDirectory)
          
          echo "Initializing Terraform..."
          terraform init

          echo "Creating Terraform plan..."
          terraform plan -out plan.out

          echo "Applying Terraform plan..."
          terraform apply -auto-approve plan.out
